// Generated by IB v0.3.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
#import <UIKit/UIKit.h>

@interface AppDelegate





-(IBAction) applicationDidFinishLaunching:(id) notification;
-(IBAction) buildWindow;

@end


@interface AppDelegate





-(IBAction) buildMenu;

@end


@interface PageDetailsViewController: PEPopoverController





-(IBAction) awakeFromNib;
-(IBAction) setup;
-(IBAction) setup_kvo_text_input;
-(IBAction) refresh_button;
-(IBAction) show_popover:(id) anchor_view;
-(IBAction) handle_input_action_button:(id) sender;
-(IBAction) hide_popover;

@end


@interface PEViewController

@property IBOutlet id frame_view;





@end


@interface PEPopoverController: NSViewController







@end


@interface MainWindowController

@property IBOutlet id page_details_vc;
@property IBOutlet id actions_barvc;





@end


@interface PageDetailsViewController

@property IBOutlet id actions_barvc;
@property IBOutlet id page_collectionvc;
@property IBOutlet id page_collection_frame_view;
@property IBOutlet id popover;
@property IBOutlet id page_details_vc;





@end


@interface BrowserWindowController

@property IBOutlet id page_details_vc;





@end



