// Generated by IB v0.3.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate

@end


@implementation AppDelegate

@end


@implementation PageDetailsViewController

@end


@implementation PEViewController

@end


@implementation PEPopoverController

@end


@implementation MainWindowController

@end


@implementation PageDetailsViewController

@end


@implementation BrowserWindowController

@end



